<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DmitryFRAMEWORK" ignored="0" name="Default test" tests="4" failures="1" timestamp="26 Jan 2017 06:26:51 GMT" time="0.124" errors="0">
  <testcase name="TC-01.01 (Summary of 1 and 2 equals 3)" time="0.021" classname="core.DPCSVTMTest"/>
  <testcase name="TC-01.02 (Summary of 3 and 4 equals 7)" time="0.002" classname="core.DPCSVTMTest"/>
  <testcase name="TC-01.03 (Summary of 5 and 6 equals 11)" time="0.001" classname="core.DPCSVTMTest"/>
  <testcase name="TC-01.04 (Summary of 7 and 8 equals 15)" time="0.008" classname="core.DPCSVTMTest">
    <failure type="java.lang.AssertionError" message="
Expected: is &amp;lt;16&amp;gt;
     but: was &amp;lt;15&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: is <16>
     but: was <15>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at core.DPCSVTMTest.test(DPCSVTMTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC-01.04 (Summary of 7 and 8 equals 15) -->
</testsuite> <!-- Default test -->
